### PR TITLE
[Technical Support] LPS-66606 and LPS-66603

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Giros,

see the comments on the original pull request in time order:

https://github.com/zsigmondrab/liferay-portal/pull/140#issue-160371192
https://github.com/zsigmondrab/liferay-portal/pull/140#issuecomment-226660368

Thank you for handling this in advance,
Zsigmond

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Giros,

I hope that you are well. Could you please take this as high priority? Because the issue came from EE customer.

Best Regards,
Hai

**Comment by giros** [comment]
Hi Yu,

Sorry for the delay, I had other high priority tasks. I will take a look at this first thing tomorrow morning (Wednesday). That means some time during your day, hopefully we will have an outcome while you are in the office.

Regards,
G

**Comment by yuhai** [comment]
Thanks. :)

**Comment by giros** [comment]
Hi Hai,

I tested the steps of LPS-66603 with your changes in place. After performing all steps, if I query the layoutrevision table, I see several new layoutrevisions got created, which seem to be identical (except their layoutRevisionId obviously). Also, more of them has the same parentlayoutRevisionId, which is weird at this point. See the content of my layoutrevision table in XML format [attached.](https://github.com/giros/liferay-portal/files/328120/layoutrevision_table.txt)

I don't really think this is intended. My understanding is that there should be only the 2 original layoutrevisions and 2 new ones that were created by the import in the last step. Can you please take a look at this and if this is the intended behavior explain why? Thank you.

Regards,
G

**Comment by yuhai** [comment]
Hi Giros,

If one layout includes three portlets, when import every portlet(updatePreferences), the fix will create one three new layoutrevision datas. Because in UI, when we edit every portlet configuration(updatePreferences), it also will create three new different layoutrevision datas. So the fix follows with UI operations. 

Regards,
Hai

**Comment by giros** [comment]
Hi Hai,

I kind of understand your point about reflecting the UI behavior (even though I still think that 1 import counts as 1 modification to a page), but the bigger problem here is that all the new layout revisions that the import creates with your fix have the same parentLayoutRevisionId, pointing to the initial revision. This would never be the case if we would make modifications manually to a page - in this case each revisions would have the previous one as their parent.

Because of this anomaly, if I go to the staging site after the import with your fix, then open the history of a page and delete the latest draft revision, the first one will become the current and not the previous. This is definitely not the intended behavior.

Please take a look at your script considering the above, and resend the pull request. Let me know if you have any questions.

Regards,
G

**Comment by yuhai** [comment]
Hi Giros,

I will follow with your guide to finish the fix (when import portlets, let it generates one revision). However, one issue blocked me. Please see LPS-66818. Without my fix, delete staging site layout's layoutrevision draft revision, it will display head (true) revision and this break inherit relation. So I need to firstly solve LPS-66818.

I will submit the three LPS together next time.

Regards,
Hai

**Comment by giros** [comment]
Thanks, Hai!

Since I will be on vacation during next week, please send your pull request to @moltam89

Regards,
G

**Pull request closed without merging**
