### PR TITLE
LPS-84715 initial import of default layoutSetPrototype won't creat default layout

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
Originally a 7.0.x fix:
https://github.com/moltam89/liferay-portal-ee/pull/62
However, resources-importer is no longer supported, we should update the source on master.

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77893. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
