### PR TITLE
LPS-98548 deleting layoutSetPrototype will only check layoutSets on the same virtual instance

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78521. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
