### PR TITLE
LPS-98548 deleting layoutSetPrototype will only check layoutSets on the same virtual instance

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Even though I said otherwise before (sorry), please make this fix by adding and using a new persistence finder instead of using dynamic query.

**Pull request closed without merging**
