### PR TITLE
LPS-98892 Staging process summary only displays the propagated pages

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Pull request closed without merging**
