### PR TITLE
LPS-74467 adding (Staging) to Staged Sites descriptiveName

### PR DESCRIPTION
**Pull request by balazssk**
Hi @giros 
I'd like to ask for your opinion on this PR.

Thanks,
Balazs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:reopen

**Comment by giros** [comment]
ci:retest

**Comment by balazssk** [comment]
oh, the staging related test failure looks valid, let me update it.

**Comment by balazssk** [comment]
ci:retest

**Comment by giros** [comment]
Hi @balazssk, seems like the same staging related test failed again.

**Comment by balazssk** [comment]
ci:retest

**Comment by balazssk** [comment]
Hi @giros,
I've fixed the staging related test failure, I don't see any reference to staging in the failing tests.

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Hi @balazssk 

I'm sorry but I completely agree with Tomcsi. We should not touch GroupImpl.getDescriptiveName() for the sake of one specific admin screen that has a bug. We should fix the wrong UI part instead.

/cc @moltam89

**Pull request closed without merging**
