### PR TITLE
LPS-98892 Staging process summary only displays the propagated pages

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77802. [See changes here.](https://github.com/giros/liferay-portal/compare/9ed46a42425e~6...9ed46a42425e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
