### PR TITLE
LPS-78411

### PR DESCRIPTION
**Pull request by balazssk**
Hi @giros 
Can you please have a look at this?

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @giros ,
Have you had a chance to look at this?

Thanks,
Balazs

**Comment by giros** [comment]
@balazssk nope, but I'm hoping to get to it this afternoon.

**Comment by balazssk** [comment]
Cheers!

**Comment by giros** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
ci:test

**Comment by balazssk** [comment]
Hi @giros ,
Seems the CI tests are failing because they can't find the updated 1.2 petra.string bundle.
Shouldn't the build check new build artifacts for dependencies after not finding them in the artifactory?

**Comment by giros** [comment]
@balazssk we need to use project dependency in this case. I'm doing this for you now and rebasing.

**Comment by giros** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1955. [See changes here.](https://github.com/giros/liferay-portal/compare/0e03e400ca82~2...0e03e400ca82) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by balazssk** [comment]
Thanks for the help @giros

**Pull request closed without merging**
